name: WhiteLister
main: ru.boomearo.whitelister.WhiteLister
version: 0.6.1
author: BoomEaro
api-version: 1.13
description: WhiteList system for offline mode servers
commands:
  whitelister:
    aliases: [whitelist, wl]
    usage: /whitelister add|remove|list
    description: Main command